### ISSUE TITLE
Delete me.

### ISSUE THREAD

**Issue by kbadk** [CMTegner/jsonml-parse#1]
The parser with input `<html></html>` returns `[ 'html' ]` as expected, but when the input ends with a linebreak `<html></html>\n`, the output becomes `[ [ 'html' ], '\n' ]`. This is inconvenient, but I realize not an actual bug in the parser: I should just trim the HTML input.

Please delete this issue.

**Comment by CMTegner** [comment]
Hey! No issue is without merit. I updated the readme to explicitly mention leading/trailing text/whitespace. Hopefully it'll prevent others from running into the same problem in the future :)
